#sudo: false
# travis-ci.org build & test configuration
language: python

matrix:
    include:
        - python: 2.7
          env: PYTHON=2.7 CONDA_PY=2 ROOT=5.34.32
        - python: 2.7
          env: PYTHON=2.7 CONDA_PY=2 ROOT=6.04
        - python: 3.4
          env: PYTHON=3.4 CONDA_PY=3 ROOT=5.34.32
        - python: 3.4
          env: PYTHON=3.4 CONDA_PY=3 ROOT=6.04
    allow_failures:
        - python: 3.4
          env: PYTHON=3.4 CONDA_PY=3 ROOT=5.34.32
#install: source ci/install.sh
install:
  - if [ "${TRAVIS_OS_NAME}" == "osx" ]; then curl --silent http://repo.continuum.io/miniconda/Miniconda${CONDA_PY}-latest-MacOSX-x86_64.sh -o miniconda.sh; fi
  - if [ "${TRAVIS_OS_NAME}" == "linux" ]; then wget -nv http://repo.continuum.io/miniconda/Miniconda${CONDA_PY}-latest-Linux-x86_64.sh -O miniconda.sh; fi

  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a # Useful for debugging any issues with conda
  - conda config --add channels http://conda.anaconda.org/NLeSC
  - conda config --set show_channel_urls yes
  - conda create -q -n testenv python=${PYTHON} root=${ROOT} root-numpy numpy matplotlib nose sphinx pytables
  - export CONDA_ENV_PATH=$HOME/miniconda/envs/testenv
  - source activate testenv
  - locate libstdc++.so.6

script: bash ci/test.sh
cache: apt
