# travis-ci.org build & test configuration
language: python
virtualenv:
    system_site_packages: true
python:
    - "2.7"
    #- "3.4"
env:
    - ROOT=5.34.18
    - ROOT=master
install: source ci/install.sh
script: bash ci/test.sh
cache: apt
